-- AlterTable
ALTER TABLE `payments` ADD COLUMN `paidAt` DATETIME(3) NULL,
    ADD COLUMN `paymentMethod` VARCHAR(191) NULL,
    ADD COLUMN `paymentUrl` TEXT NULL,
    MODIFY `status` ENUM('PENDING', 'PROCESSING', 'PAID', 'FAILED', 'REFUNDED') NOT NULL DEFAULT 'PENDING';
